spring:
  application:
      name:config-default
server:
   port:9090
my:    
  greeting:
    message:  helloworld from config server-main
eureka:
  instance:
    prefer-ip-address: true
   client:
      registerWithEureka: true
      fetchRegistry: true
      service-url: http://localhost:8761/eureka
      
